--liquibase formatted sql
--changeset rakhmanovaa:0001_init stripComments:false dbms:postgresql endDelimiter:;;
--comment: 0001_init

create table items (
    id bigint generated by default as identity,
    name varchar(50) not null,
    description varchar(1024) not null,
    price numeric(10, 2) not null,
    image_path varchar(100) not null,
    constraint pk_item_id primary key (id)
);

create table orders (
    id bigint generated by default as identity,
    user_id bigint not null,
    is_paid boolean default false,
    constraint pk_order_id primary key (id)
);

create index idx_order_user_id on orders (user_id);

create table orderitems (
    id bigint generated by default as identity,
    order_id bigint not null,
    item_id bigint not null,
    count integer not null,
    constraint pk_orderitems_id primary key (id),
    constraint fk_order_id foreign key (order_id) references orders(id),
    constraint fk_item_id foreign key (item_id) references items(id),
    constraint uq_orderitems_order_id_item_id unique (order_id, item_id)
);

create index idx_orderitems_order_id on orderitems (order_id);