spring:
  r2dbc:
    url: ${SPRING_DATASOURCE_URL:r2dbc:postgresql://localhost:5432/myshopdb}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50
      max-idle-time: 30s
      max-life-time: 10m
      validation-query: SELECT 1
  liquibase:
    enabled: true
    url: ${LIQUIBASE_DATASOURCE_URL:jdbc:postgresql://localhost:5432/myshopdb}
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}

logging:
  level:
    ru.rakhmanov.myshop: DEBUG
    org.liquibase: INFO

