spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myshopdb
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    enabled: true

logging:
  level:
    ru.rakhmanov.myshop: DEBUG
    org.liquibase: INFO

